# Generated by Django 5.2.1 on 2026-01-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_user_auth_api_us_email_c29b6b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pincode',
        ),
    ]
